fix: adds accessibility to code-group component
vuejs/vuepress pull request #2630
Opened 2020-09-29 01:28 UTC by lbenie

**Summary**

Fixes the `code-group` component by wrapping the buttons in a list for accessibility purpose.

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of default theme, please provide the **before/after** screenshot:

Before on the left
After on the right
![image](https://user-images.githubusercontent.com/7316046/94502058-460d4700-01d1-11eb-8649-97c328e78dff.png)

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2020-10-01 16:23 UTC, d-pollard requested changes
Do you happen to have an a11y resource that would explain how this improves accessibility vs what was previously there?

Other than the comment I made, it looks good!

2020-10-01 16:23 UTC, d-pollard commented on packages/@vuepress/theme-default/global-components/CodeGroup.vue
> +    padding-bottom: 5px;
taking this out causes the bottom to get clipped on some of the code group tabs:

![Screen Shot 2020-10-01 at 11 17 56 AM](https://user-images.githubusercontent.com/16292606/94835846-d7e6a100-03d7-11eb-8397-8df21ba87bed.png)

2020-10-01 16:44 UTC, lbenie commented
> Do you happen to have an a11y resource that would explain how this improves accessibility vs what was previously there?
> 
> Other than the comment I made, it looks good!

Sure!

Some guidelines about `list` usage in regards to WCAG AA

https://www.a11yproject.com/checklist/#use-list-elements-lesscodegreaterolless/codegreater-lesscodegreaterulless/codegreater-and-lesscodegreaterdlless/codegreater-elements-for-list-content

Since the component is `listing` a bunch of related buttons, it makes more sense to group them under a list tag.

Although thinking on the nav element should be removed since it relates to navigation links. I'll update the PR to remove the `nav` and fix the CSS

2020-10-01 23:22 UTC, lbenie commented
@d-pollard 

I've updated the PR with the requested changes let me know if I need to do something else :)

2020-10-01 23:42 UTC, d-pollard approved these changes
Looks good! Thank you for making these changes!

2020-10-02 10:47 UTC, merged

2020-10-02 10:48 UTC, bencodezen commented
Thanks @lbenie for your work on this! Appreciate it!