code-group component appearance optimization
vuejs/vuepress pull request #2632
Opened 2020-09-29 14:16 UTC by liyuj

**Summary**
When the code-group component is selected, there is a white border line, which is hard to see
The height of the tab is too high

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [*] Other, please describe:
css is changed.
If changing the UI of default theme, please provide the **before/after** screenshot:
before:
![image](https://user-images.githubusercontent.com/9244802/94570265-41b05f00-02a1-11eb-8a1d-a514605cbe51.png)

after:
![image](https://user-images.githubusercontent.com/9244802/94570355-5a207980-02a1-11eb-978b-f989b83321ed.png)

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ *] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ *] Chrome
- [ *] Firefox
- [ *] Safari
- [ *] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

2020-10-01 16:54 UTC, d-pollard requested changes
Thanks for the contribution! 

After going over the code and reading a few a11y articles, I believe this would impact accessibility negatively:

> **Do We Really Need the Outlines?**
> Yes, you can remove them, but you should understand one thing first:
You should never remove the outline for users using a keyboard to surf the page. People that only use the keyboard need to understand where they are focused; with the mouse or touch you won’t have this problem.

-[Source article](https://medium.com/better-programming/a11y-never-remove-the-outlines-ee4efc7a9968)

Instead of this change, the article goes onto mention a few a11y-safe options, and this project would strongly consider those if you'd like to make a PR for it.

Alternatively, for your own project, you should be able to override the default styling in `docs/.vuepress/styles/index.styl` and add these styles there to achieve the same net effect

Let me know if you have any questions about anything I've mentioned here

We appreciate your work on this and hope to see additional PRs in the future!

2020-10-01 17:02 UTC, bencodezen commented
Thank you for the thoughtful review @d-pollard and your time @liyuj!

2020-10-01 17:02 UTC, closed without merging

2020-10-02 14:03 UTC, liyuj commented
Thank you for your explanation.
In addition, there is another change to this PR, namely:

**padding-top: 3px;**

The height of the tab bar looks too high. Can make it smaller?

This style doesn't seem to work palette.styl overwrite.
@bencodezen @d-pollard @duncan

2020-10-02 19:14 UTC, d-pollard commented
@liyuj mind submitting an issue with screenshots?